"""Planted bugs: each swaps one piece of SQL text in one ETL file (mutation-style).
`detectors` = checks that MUST fail when this bug is present (tests enforce it)."""

BUGS = {
    "B1": dict(file="1_stage.sql", type="Wrong join type",
               old="LEFT JOIN src_accounts", new="JOIN src_accounts",
               what="Orders with an unknown account silently disappear (INNER instead of LEFT join); their executions and allocations are rejected with them",
               detectors=["FL01", "NL03"]),
    "B2": dict(file="1_stage.sql", type="Missing filter value",
               old="WHERE h.venue IN ('VEN_A','VEN_B','VEN_C')", new="WHERE h.venue IN ('VEN_A','VEN_B')",
               what="A valid venue was left out of the IN list, so its orders are dropped",
               detectors=["FL01"]),
    "B3": dict(file="5_publish.sql", type="Join key mismatch / duplicates",
               old="ON s.order_id = o.order_id AND s.trade_date = o.trade_date;", new="ON s.order_id = o.order_id;",
               what="Publish joins the change scope on order_id only (trade_date missing), so unchanged rows of other dates are published again",
               detectors=["DU03", "PB03"]),
    "B4": dict(file="1_stage.sql", type="Stale data (wrong dedup order)",
               old="ORDER BY h.event_id DESC", new="ORDER BY h.event_id ASC",
               what="Dedup keeps the FIRST event instead of the latest, so old status/qty is loaded",
               detectors=["DD01", "ST01"]),
    "B5": dict(file="2_orders.sql", type="Versioning logic",
               old="THEN lastv.order_version + 1", new="THEN lastv.order_version",
               what="Version not incremented when the source batch changes, so the change looks already published and is lost",
               detectors=["VR01", "DF01"]),
    "B6": dict(file="3_executions.sql", type="Transformation / mapping",
               old="THEN 'OTC'", new="THEN 'OFFX'",
               what="OFFX to OTC market mapping does nothing",
               detectors=["TR02"]),
    "B7": dict(file="4_allocations.sql", type="Calculation error",
               old="w.qty, w.price", new="w.qty, w.price + 1",
               what="Allocation price is off by +1",
               detectors=["ST03"]),
    "B8": dict(file="1_stage.sql", type="NULL handling",
               old="COALESCE(d.client_name, 'UNKNOWN')", new="d.client_name",
               what="Default for unknown accounts removed, so client_name is NULL",
               detectors=["NL02", "NL03"]),
    "B9": dict(file="3_executions.sql", type="Precision loss",
               old="w.qty, w.price,", new="w.qty, ROUND(w.price, 0),",
               what="Execution price rounded to whole numbers (1500.25 becomes 1500)",
               detectors=["ST02"]),
    "B10": dict(file="1_stage.sql", type="Boundary / off-by-one date",
                old="AND h.trade_date BETWEEN '2024-01-14' AND '2024-01-15'",
                new="AND h.trade_date > '2024-01-14' AND h.trade_date <= '2024-01-15'",
                what="Start date made exclusive, so the first day of the window is lost",
                detectors=["BD01", "FL01"]),
}

# Extra bugs used ONLY by the practice grader (not in the report). Each is caught by one practice exercise.
PRACTICE_BUGS = {
    "X1": dict(file="schema.sql", type="Schema drift",
               old="CREATE TABLE tgt_executions (\n    exec_id INTEGER, order_id INTEGER, trade_date TEXT, exec_version INTEGER,\n    source_batch_id TEXT, qty INTEGER, price REAL, market_code TEXT);",
               new="CREATE TABLE tgt_executions (\n    exec_id INTEGER, order_id INTEGER, trade_date TEXT, exec_version INTEGER,\n    source_batch_id TEXT, qty INTEGER, price INTEGER, market_code TEXT);",
               what="Target price column declared INTEGER instead of REAL"),
    "X2": dict(file="1_stage.sql", type="Domain violation",
               old="h.qty, h.status, h.side_code,", new="h.qty, LOWER(h.status), h.side_code,",
               what="Order status loaded in lower case"),
    "X3": dict(file="4_allocations.sql", type="Range violation",
               old="w.exec_id, w.account_id, w.qty", new="w.exec_id, w.account_id, -w.qty",
               what="Allocation qty sign flipped (negative)"),
    "X4": dict(file="3_executions.sql", type="Aggregate mismatch",
               old="w.source_batch_id, w.qty, w.price,", new="w.source_batch_id, w.qty / 2, w.price,",
               what="Execution qty halved"),
    "X5": dict(file="5_publish.sql", type="Ghost record",
               old="-- Inner join each work table to the scope; only matching rows are published.",
               new="-- Inner join each work table to the scope; only matching rows are published.\nINSERT INTO tgt_orders VALUES (9999,'2024-01-15',1,'B5',1,'NEW','GHOST','BUY');",
               what="A row with no source is published"),
    "X6": dict(file="2_orders.sql", type="Incremental / version skip",
               old="THEN lastv.order_version + 1", new="THEN lastv.order_version + 2",
               what="Changed order jumps two versions"),
}
ALL_BUGS = {**BUGS, **PRACTICE_BUGS}
